[book]
authors = ["Sylvain Wallez"]
multilingual = false
src = "src"
title = "Introduction to Rust"

[output.html.search]
enable = true

[output.html.playground]
editable = true
line-numbers = true

[build]
create-missing = true
build-dir = "docs"

[rust]
edition = "2024"
